"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.metadata = void 0;
exports.default = RootLayout;
const google_1 = require("next/font/google");
const ui_components_1 = require("@kudiflow/ui-components");
const OfflineBanner_1 = require("../components/OfflineBanner");
const I18nProvider_1 = require("../components/I18nProvider");
require("./globals.css");
const customTheme = {
    primaryColor: '#22c55e',
    secondaryColor: '#0f172a',
    backgroundColor: '#020617',
    textColor: '#e5e7eb',
    borderRadius: '16px',
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    spacingUnit: '0.9rem',
};
const geistSans = (0, google_1.Geist)({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});
const geistMono = (0, google_1.Geist_Mono)({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});
exports.metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};
function RootLayout({ children, }) {
    return (<html lang="en" suppressHydrationWarning>
      <head>
        <ui_components_1.ThemeScript />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <I18nProvider_1.I18nProvider>
          <ui_components_1.KudiFlowProvider theme={customTheme} defaultMode="system">
            <ui_components_1.TransactionProvider>
              <OfflineBanner_1.OfflineBanner />
              {children}
            </ui_components_1.TransactionProvider>
          </ui_components_1.KudiFlowProvider>
        </I18nProvider_1.I18nProvider>
      </body>
    </html>);
}
//# sourceMappingURL=layout.js.map