/**
 * Failure scenarios recognized by the Soroban Transfer Recovery Planner (#619).
 *
 * Each scenario maps a class of failures to one or more recovery strategies
 * and a default severity so the planner can prioritize the response.
 */
export type RecoveryScenario =
  | 'TIMEOUT'
  | 'INSUFFICIENT_FEE'
  | 'SEQUENCE_MISMATCH'
  | 'ACCOUNT_ERROR'
  | 'CONTRACT_ERROR'
  | 'NETWORK_ERROR'
  | 'UNKNOWN';

export const RECOVERY_SCENARIOS: readonly RecoveryScenario[] = [
  'TIMEOUT',
  'INSUFFICIENT_FEE',
  'SEQUENCE_MISMATCH',
  'ACCOUNT_ERROR',
  'CONTRACT_ERROR',
  'NETWORK_ERROR',
  'UNKNOWN',
] as const;

export type RecoverySeverity = 'low' | 'medium' | 'high' | 'critical';

/**
 * A single recovery action generated by the planner.
 * Discriminated by `type` so consumers can branch on the kind of step.
 */
export type RecoveryAction =
  | {
      type: 'retry';
      /** 1-based attempt number this action represents. */
      attempt: number;
      /** Backoff delay in milliseconds before the retry. */
      delayMs: number;
      /** Optional fee bump (stroops) when resubmitting with more fee. */
      feeBumpStroops?: number;
    }
  | {
      type: 'resubmit';
      /** Suggested delay (ms) before resubmitting to refresh ledger state. */
      delayMs: number;
    }
  | {
      type: 'increase_fee';
      /** Additional stroops to add to the base fee. */
      extraStroops: number;
      /** New base fee in stroops after the bump. */
      newBaseFeeStroops: number;
    }
  | {
      type: 'manual_review';
      /** Short rationale that explains why human review is required. */
      reason: string;
    }
  | {
      type: 'cancel';
      /** Why the transfer should be cancelled outright. */
      reason: string;
    };

/**
 * Structured description of a transfer failure passed to the planner.
 */
export interface TransferFailure {
  /** Stellar transaction hash of the failed transfer. */
  transferHash: string;
  /** Source chain (e.g. "stellar"). */
  sourceChain: string;
  /** Destination chain. */
  destinationChain: string;
  /** Free-form reason returned by the bridge or Soroban runtime. */
  reason: string;
  /** Base fee that was used (stroops). */
  baseFeeStroops?: number;
  /** Number of attempts already performed before this failure. */
  previousAttempts?: number;
  /** Unix timestamp (ms) when the failure was observed. */
  failedAt?: number;
}

/**
 * Output of the planner: the classified scenario plus the ordered
 * sequence of recovery actions to take.
 */
export interface RecoveryPlan {
  transferHash: string;
  scenario: RecoveryScenario;
  severity: RecoverySeverity;
  /** Human-readable explanation of why this scenario was chosen. */
  rationale: string;
  actions: RecoveryAction[];
  /** True when the plan can be executed without human review. */
  automatable: boolean;
  /** Unix timestamp (ms) when the plan was generated. */
  generatedAt: number;
}

export interface RecoveryPlannerConfig {
  /** Max retry attempts to include in auto-generated plans. Default: 3 */
  maxRetries?: number;
  /** Initial backoff (ms) between retries. Default: 1000 */
  initialDelayMs?: number;
  /** Backoff multiplier between retries. Default: 2 */
  backoffMultiplier?: number;
  /** Cap on any individual backoff delay (ms). Default: 30_000 */
  maxDelayMs?: number;
  /** Base fee in stroops used when the failure reason doesn't carry one. Default: 100 */
  defaultBaseFeeStroops?: number;
  /** Extra stroops applied on the increase_fee action. Default: 1000 */
  feeBumpStroops?: number;
}

export const DEFAULT_RECOVERY_PLANNER_CONFIG: Required<RecoveryPlannerConfig> = {
  maxRetries: 3,
  initialDelayMs: 1_000,
  backoffMultiplier: 2,
  maxDelayMs: 30_000,
  defaultBaseFeeStroops: 100,
  feeBumpStroops: 1_000,
};

/**
 * Result of `automate()` — one entry per attempted action, in plan order.
 */
export interface AutomationStepResult {
  action: RecoveryAction;
  attempted: boolean;
  success: boolean;
  error?: string;
}

export interface AutomationResult {
  plan: RecoveryPlan;
  steps: AutomationStepResult[];
  /** True when the plan was automated and all steps succeeded. */
  recovered: boolean;
  /** True when automation stopped at a `manual_review` action. */
  requiresHumanReview: boolean;
  /** Set when automation was cancelled because `maxAutomationSteps` was reached. */
  truncated?: boolean;
}

/**
 * Function signature for executing a recovery action against the bridge.
 * Returns the recovery transaction hash on success, or throws.
 */
export type RecoveryExecutor = (action: RecoveryAction, failure: TransferFailure) => Promise<string>;
